### PATCH /v1/me
PATCH http://localhost:5435/v1/me
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTMsImlhdCI6MTYyMTM1NjkxOCwiZXhwIjoxNjIxMzU2OTc4fQ.ux7JRV2wROEAp8p0lLSfN4kEbnTj6G13FWWtXxmjm0A
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTMsImlhdCI6MTYyMTM1NjkxOCwiZXhwIjoxNjIxMzU3MjE4fQ.Uy8PhVvjJE6lLnzd2fuZixYvjRfr0JnadZtDlavrcE8
Content-Type: application/json

{
    "email" : "lulu@lulu.com",
    "password" : "lulu",
    "newPassword" : "azerty",
    "userId" : 53
}

#------------------------------------------------

### GET /v1/login
POST http://localhost:5435/v1/login
Content-Type: application/json

{
    "email" : "lulu@lulu.com",
    "password" : "lulu"
}

#------------------------------------------------

### GET /v1/channel/:id (try to access to a resource)
GET http://localhost:5435/v1/channel/1
Content-Type: application/json

#------------------------------------------------

### GET /v1/logout
POST http://localhost:5435/v1/logout
Content-Type: application/json

{
    "id" : 51
}

